version: "3"

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --sql-mode="ANSI_QUOTES,TRADITIONAL" --default-time-zone='-03:00' --innodb_strict_mode=0
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
